services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./sse:/sse
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: db
    working_dir: /sse
    depends_on:
      - redis
    command: >
      sh -c "
        poetry config virtualenvs.create false &&
        poetry install --no-root &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        daphne -b 0.0.0.0 -p 8000 config.asgi:application
      "

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
    volumes:
      - ./sse:/sse
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: db
    working_dir: /sse
    command: >
      sh -c "
        poetry config virtualenvs.create false &&
        poetry install --no-root &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        celery --app=config worker -l INFO
      "
    depends_on:
      - redis

  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - celery
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
